import { Perfume } from '@/types/perfume'

export const mockPerfumes: Perfume[] = [
  // ─── ÁRABES ───────────────────────────────────────────────────────────────
  {
    id: '1',
    name: 'Ameer Al Oudh',
    brand: 'Lattafa',
    description: 'Una fragancia oriental profunda con notas de oud, especias y madera de sándalo. Perfecta para ocasiones especiales, su sillage majestuoso perdura horas en la piel.',
    price: 45,
    category: 'arabe',
    gender: 'hombre',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [50, 100],
    notes_top: ['Bergamota', 'Cardamomo'],
    notes_heart: ['Oud', 'Rosa'],
    notes_base: ['Sándalo', 'Almizcle', 'Ámbar'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Shaghaf Oud Aswad',
    brand: 'Swiss Arabian',
    description: 'Una composición audaz y oscura que combina oud ahumado con especias orientales y maderas preciosas. Intensidad y sofisticación en cada nota.',
    price: 65,
    original_price: 80,
    category: 'arabe',
    gender: 'hombre',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [100],
    notes_top: ['Azafrán', 'Rosa Negra'],
    notes_heart: ['Oud Negro', 'Pachulí'],
    notes_base: ['Ámbar', 'Sándalo', 'Almizcle'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'La Yuqawam',
    brand: 'Rasasi',
    description: 'Una fragancia unisex que equilibra flores exóticas con maderas cálidas y oud suave. Elegancia oriental accesible con una longevidad excepcional.',
    price: 55,
    category: 'arabe',
    gender: 'unisex',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [50, 100, 200],
    notes_top: ['Neroli', 'Bergamota'],
    notes_heart: ['Oud', 'Rosa', 'Jazmín'],
    notes_base: ['Sándalo', 'Cedro', 'Vetiver'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Yara Moi',
    brand: 'Lattafa',
    description: 'Fragancia femenina dulce y cautivadora con flores blancas y vainilla cremosa sobre base almizclada. Un abrazo en forma de perfume.',
    price: 40,
    category: 'arabe',
    gender: 'mujer',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [100],
    notes_top: ['Pera', 'Bergamota', 'Fresia'],
    notes_heart: ['Jazmín', 'Rosa', 'Lila'],
    notes_base: ['Vainilla', 'Almizcle Blanco', 'Pachulí'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Oud For Glory',
    brand: 'Ard Al Zaafaran',
    description: 'Una oda al oud con capas de especias cálidas, resinas preciosas y maderas nobles. Longevidad excepcional, proyección imponente.',
    price: 35,
    original_price: 50,
    category: 'arabe',
    gender: 'unisex',
    concentration: 'Parfum',
    volume_ml: 100,
    available_volumes: [100],
    notes_top: ['Azafrán', 'Canela'],
    notes_heart: ['Oud Puro', 'Sándalo'],
    notes_base: ['Ámbar Gris', 'Resina', 'Almizcle'],
    in_stock: false,
    featured: false,
    created_at: new Date().toISOString(),
  },

  // ─── DISEÑADOR ────────────────────────────────────────────────────────────
  {
    id: '6',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    description: 'Una oda al hombre libre. Aromática y fresca con madera y tonos cítricos vibrantes. El clásico moderno por excelencia, atemporal y elegante.',
    price: 125,
    category: 'disenador',
    gender: 'hombre',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [50, 100, 150],
    notes_top: ['Limón', 'Pomelo', 'Menta'],
    notes_heart: ['Jazmín', 'Jengibre', 'Nuez Moscada'],
    notes_base: ['Sándalo', 'Cedro', 'Vetiver'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Sauvage',
    brand: 'Dior',
    description: 'Salvaje y noble. Bergamota de Calabria y Ambroxan mineral evocan el desierto en hora azul. La fragancia masculina más vendida del mundo.',
    price: 140,
    category: 'disenador',
    gender: 'hombre',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [60, 100, 200],
    notes_top: ['Bergamota de Calabria', 'Pimienta'],
    notes_heart: ['Lavanda Sichuan', 'Geranio'],
    notes_base: ['Ambroxan', 'Cedro de Virginia'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    description: 'Glamour oscuro y adictivo. Café negro, flores blancas y vainilla en una composición audaz que redefine la feminidad contemporánea.',
    price: 115,
    category: 'disenador',
    gender: 'mujer',
    concentration: 'EDP',
    volume_ml: 90,
    available_volumes: [30, 50, 90],
    notes_top: ['Pera', 'Grosella Negra', 'Flor de Naranjo'],
    notes_heart: ['Café', 'Jazmín', 'Almendro Amargo'],
    notes_base: ['Vainilla', 'Pachulí', 'Cedro'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    description: 'La felicidad como elección. Un bouquet de iris, pralinado y vainilla que revolucionó la perfumería femenina. Icónico e inconfundible.',
    price: 110,
    original_price: 130,
    category: 'disenador',
    gender: 'mujer',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [30, 50, 75, 100],
    notes_top: ['Grosella Negra', 'Pera'],
    notes_heart: ['Iris', 'Jazmín', 'Flor de Naranjo'],
    notes_base: ['Praliné', 'Vainilla', 'Pachulí', 'Tonka'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Acqua di Giò',
    brand: 'Giorgio Armani',
    description: 'El Mediterráneo en un frasco. Frescura marina, notas acuáticas y madera blanca. La fragancia masculina más icónica del mundo desde 1996.',
    price: 95,
    category: 'disenador',
    gender: 'hombre',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [40, 75, 100],
    notes_top: ['Bergamota', 'Mandarina', 'Lima'],
    notes_heart: ['Mar', 'Romero', 'Vetiver'],
    notes_base: ['Pachulí', 'Musgo Marino', 'Almizcle'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },

  // ─── NICHO ────────────────────────────────────────────────────────────────
  {
    id: '11',
    name: 'Replica Jazz Club',
    brand: 'Maison Margiela',
    description: 'Cierra los ojos y estás ahí. Ron, tabaco, vetiver y almizcle evocan una noche de jazz en Nueva Orleans. Experiencia más que fragancia.',
    price: 190,
    category: 'nicho',
    gender: 'unisex',
    concentration: 'EDT',
    volume_ml: 100,
    available_volumes: [30, 100],
    notes_top: ['Bergamota', 'Anís'],
    notes_heart: ['Ron de Jamaica', 'Tabaco', 'Vetiver'],
    notes_base: ['Vainilla de Madagascar', 'Almizcle Blanco'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: "Bal d'Afrique",
    brand: 'Byredo',
    description: 'Energía y libertad africana. Bergamota, neroli, violeta y cálamo aromático en una sinfonía alegre y sofisticada. Arte en estado gaseoso.',
    price: 235,
    category: 'nicho',
    gender: 'unisex',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [50, 100],
    notes_top: ['Bergamota Africana', 'Neroli'],
    notes_heart: ['Violeta', 'Jazmín Africano', 'Cálamo'],
    notes_base: ['Cedro', 'Vetiver', 'Almizcle Blanco'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Santal 33',
    brand: 'Le Labo',
    description: 'Sándalo australiano, cedro, cardamomo y cuero. La fragancia de culto que redefinió la perfumería de nicho. Adictiva, unisex, imposible de ignorar.',
    price: 275,
    category: 'nicho',
    gender: 'unisex',
    concentration: 'EDP',
    volume_ml: 100,
    available_volumes: [50, 100],
    notes_top: ['Cardamomo', 'Iris', 'Violeta'],
    notes_heart: ['Sándalo Australiano', 'Cedro de Virginia', 'Ambrette'],
    notes_base: ['Cuero', 'Cashmere Wood', 'Almizcle'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Oud for Greatness',
    brand: 'Initio Parfums',
    description: 'La máxima expresión del oud. Oud laotiano, azafrán y ámbar gris. Para quienes no aceptan límites. La grandeza tiene un aroma.',
    price: 395,
    category: 'nicho',
    gender: 'unisex',
    concentration: 'EDP',
    volume_ml: 90,
    available_volumes: [90],
    notes_top: ['Azafrán', 'Bergamota'],
    notes_heart: ['Oud Laotiano', 'Sándalo'],
    notes_base: ['Ámbar Gris', 'Almizcle Animal'],
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },

  // ─── OTROS ────────────────────────────────────────────────────────────────
  {
    id: '15',
    name: 'Wonder Rose',
    brand: 'Zara',
    description: 'Elegancia accesible. Rosa fresca, peonía y almizcle en una fragancia cotidiana perfecta para la mujer moderna. Sencilla y encantadora.',
    price: 18,
    category: 'otros',
    gender: 'mujer',
    concentration: 'EDT',
    volume_ml: 80,
    available_volumes: [80],
    notes_top: ['Rosa', 'Bergamota'],
    notes_heart: ['Peonía', 'Jazmín'],
    notes_base: ['Almizcle Blanco', 'Cedro'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Chrome',
    brand: 'Azzaro',
    description: 'Energía urbana y modernidad. Notas acuáticas, especiadas y amaderadas para el hombre dinámico del siglo XXI. Clásico y versátil.',
    price: 55,
    original_price: 70,
    category: 'otros',
    gender: 'hombre',
    concentration: 'EDT',
    volume_ml: 100,
    available_volumes: [30, 50, 100, 200],
    notes_top: ['Bergamota', 'Anís', 'Neroli'],
    notes_heart: ['Cardamomo', 'Cuero', 'Mimosa'],
    notes_base: ['Cedro del Himalaya', 'Sándalo', 'Almizcle'],
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
]
